sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: space-takeout
    region: cn-beijing
#    access-key-id: ${OSS_ACCESS_KEY_ID:}
#    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
  wechat:
    appid: YOUR_APPID_HERE
    secret: YOUR_SECRET_HERE